baseURL = 'https://w3ds-docs.github.io/w3ds-docs/'
languageCode = 'en-us'
title = 'W3DS TRL7 Documentation'
theme = 'hugo-book'

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = 'docs'
  BookRepo = 'https://github.com/w3ds-docs/w3ds-docs'
  BookEditPath = 'edit/main/content'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
